--ozone-platform=wayland
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,Vulkan,ThrottleDisplayNoneAndVisibilityHiddenCrossOriginIframes,BackForwardCache
--disable-features=Vulkan
--disable-gpu-vulkan
--ozone-platform-hint=auto
--disable-gpu-driver-bug-workarounds
--ignore-gpu-blocklist
--enable-zero-copy
--active-gpu-device=pci-0000:00:02.0
--gpu-testing-vendor-id=0x8086
--gpu-testing-device-id=0x9b41
