# Gruvbox Dark Palette
# Background: #282828 (bg)
# Foreground: #ebdbb2 (fg)
# Red:        #cc241d
# Green:      #98971a
# Yellow:     #d79921
# Blue:       #458588
# Aqua:       #689d6a

general {
    lock_cmd = pidof hyprlock || WLR_DRM_DEVICES=/dev/dri/card1 hyprlock
    no_fade_in = false
    grace = 0
    disable_loading = true
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = <span foreground="##d79921">Scan Finger...</span>
    fingerprint:present_message = <span foreground="##689d6a">Authenticating...</span>
}

background {
    monitor =
    # Use 'screenshot' for a blurred look of your current desktop
    path = screenshot
    #path = ~/.config/hypr/my_gruv_bg.png
    color = rgba(40, 40, 40, 1.0) # Gruvbox bg
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M %p")"
    color = rgb(235, 219, 178) # Gruvbox fg
    font_size = 64
    font_family = Inconsolata Nerd Font Mono, Inconsolata
    position = 0, 80
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 1250, 250
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    
    # Colors
    outer_color = rgb(69, 133, 136)      # Blue
    inner_color = rgb(40, 40, 40)       # bg
    font_color = rgb(235, 219, 178)     # fg
    fade_on_empty = true
    placeholder_text = <i>Password or Fingerprint...</i>
    
    # Feedback Colors
    check_color = rgb(215, 153, 33)      # Yellow (Checking)
    fail_color = rgb(204, 36, 29)       # Red (Fail)
    capslock_color = rgb(214, 93, 14)    # Orange
    
    position = 0, -200
    halign = center
    valign = center
}
